### PR TITLE
Add script to run tests and get Java code coverage

### PR DESCRIPTION
**Pull request by bruce-k4**

### CODE REVIEW

**Review by fantareinos — APPROVED** [review]
I was gonna ask if you tested this, but how do you test the thing that runs the tests? 🤣

**Comment by RobertFischer** [comment]
> I was gonna ask if you tested this, but how do you test the thing that runs the tests? 🤣

The same way you test anything else...

**Comment by bruce-k4** [comment]
As Anurag should know by now, I ran the script multiple times before I ever pushed the code, much less submitted a PR for review. In fact, the first time I ran it resulted in a license header violation, which is why I knew to modify the `pom.xml`.

And, no, I'm not going to write tests for the tests. ;-)

**Review by rshannonsmith-k4 — APPROVED** [review]

**Comment by rshannonsmith-k4** [comment]
Test Inception. Test the code.  Test the test code that tests the code.  Test the test code that tests the test code that tests the code.

**Comment by bruce-k4** [comment]
> Test Inception. Test the code. Test the test code that tests the code. Test the test code that tests the test code that tests the code.

Exactly. _Ad infinitum_.

**Comment by RobertFischer** [comment]
This is where the CI server comes in: it’s an objective third party that can verify the tests actually pass.

**Comment by bruce-k4** [comment]
> This is where the CI server comes in: it’s an objective third party that can verify the tests actually pass.

You're preaching to the choir. I'm just waiting on Anurag to finish the implementation of the CI server. ;-)

And, in case there are any doubts that I ran the tests, I'm attaching the output below. 

*NOTE 1*: I just pulled the changes in this PR into my local `master` to run these, but I did run them--repeatedly--in the feature branch before I pushed it for review. 

*NOTE 2*: While I agree that having a CI server does this would be awesome, the short story is we currently don't have that set up, so kicking off automated tests manually is better than not running them at all--especially since I inherited this project and it had NO unit tests at all.

*NOTE 3*: Crawl. Walk. Run.

*NOTE 4*: This PR is done.

**Comment by bruce-k4** [comment]
[temp-test-output.txt](https://github.com/k4connect/thingsboard-gateway/files/3049541/temp-test-output.txt)

**Pull request merged**
